[workspace]
members = [
    "crates/cervo",
    "crates/cervo-cli",
    "crates/cervo-asset",
    "crates/cervo-core",
    "crates/cervo-nnef",
    "crates/cervo-onnx",
    "crates/cervo-runtime",
]

exclude = [ "benchmarks/perf-test" ]
resolver = "2"

[workspace.dependencies]
tract-core = { version = "=0.21.1,<0.21.4" }
tract-hir = { version = "0.21" }
tract-nnef = { version = "0.21" }
tract-onnx =  { version = "0.21" }
