[workspace]
members = [
    "crates/cervo",
    "crates/cervo-asset",
    "crates/cervo-core",
    "crates/cervo-nnef",
    "crates/cervo-onnx",
    "crates/cervo-runtime",
]

exclude = [ "benchmarks/perf-test" ]

[patch.crates-io]
tract-onnx = { version="0.19.3-pre", git = "https://github.com/sonos/tract", rev = "e8f82bcfe250e0786ea4cd0df049c3d4faf064b4" }
tract-nnef = { version="0.19.3-pre", git = "https://github.com/sonos/tract", rev = "e8f82bcfe250e0786ea4cd0df049c3d4faf064b4" }
tract-hir = { version="0.19.3-pre", git = "https://github.com/sonos/tract", rev = "e8f82bcfe250e0786ea4cd0df049c3d4faf064b4" }
tract-core = { version="0.19.3-pre", git = "https://github.com/sonos/tract", rev = "e8f82bcfe250e0786ea4cd0df049c3d4faf064b4" }
