[package]
name = "perf-test"
version = "0.0.0"
edition = "2018"
license = "LicenseRef-Embark-Proprietary"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
anyhow = { version = "1.0"}
tractor-onnx = { path = "../../crates/tractor-onnx" }
tractor-nnef = { path = "../../crates/tractor-nnef" }
tractor = { path = "../../crates/tractor" }
structopt = "0.3.11"
perchance = "*"
