on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build & Publish Release Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build release binary
        run: cargo build --release --bin cervo
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/cervo
